packaging_format = 2

id = "simplytranslate"
name = "Simply Translate"
description.en = "Web interface for many translation engine: DeepL, Reverso, ICIBA, Google Translate, and LibreTranslate."
description.id = "Antarmuka web mesin penerjemahan: DeepL; Reverso; ICIBA; Google Translate; dan LibreTranslate."

version = "2023.4.9~ynh1"

maintainers = ["the7thNightmare"]

[upstream]
license = "AGPL-3.0"
website = "https://simple-web.org/projects/simplytranslate.html"
code = "https://codeberg.org/SimpleWeb/SimplyTranslate-Web"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "100M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/simplytranslate"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/SimpleWeb/SimplyTranslate-Web/archive/d95fed97bf354a92d242f16529712ba59ee54eb0.tar.gz"
        sha256 = "87360d28cb849e99184b68115bbecc4c92500cf3b940abbcb05cfd17f2f7fc86"
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3 python3-venv git"
